apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 7
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
#        image: phico/guestbook:1.0
        image: docker.io/ibmcom/guestbook:v1
        ports:
        - containerPort: 3000
