apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
#        image: phico/guestbook:1.0
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2  # Image publik
        ports:
        - containerPort: 3000
